README.md, templates.json
=> Add the drupal template

README.md, templates.json
=> Add the magento 2 template

README.md, templates.json
=> Add wowza template

templates.json
Add a template for a Docker registry.
=> Add registry template

templates.json
=> Add the mongo template

README.md, templates.json
=> Add redis template

README.md, templates.json
=> Add the ubuntu template

README.md, templates.json
=> Add the debian template

README.md, templates.json
=> Add the HAProxy template

README.md, templates.json
=> Add the elasticsearch template

README.md, templates.json
=> Add the jenkins template

README.md, templates.json
=> feat(template): add plone template

README.md, templates.json
=> feat(template): add cockroachdb template

templates.json
=> feat(template): add urbackup template

templates.json
=> feat(templates): add community server template

templates.json
Add a parameter to add jenkins opts ( --prefix for example )
=> allow to add jenkins opts

templates.json
Switch MSSQL/Linux from "latest" to new label "2016-GA"
=> Switch MSSQL/Linux label

templates.json
Fix default path used by nginx conf /var/www/html -> /usr/share/nginx/html
=> fix(template): nginx volume path

stacks/ironfunctions/docker-stack.yml, templates.json
This PR adds new templates for open.iron.io:
* A stack template with API & UI bundled
* A container template for IronFunctions API
* A container template for IronFunctions UI
=> feat(templates): add IronFunction templates

README.md, stacks/sematext-agent-docker/docker-stack.yml, templates.json
Add container and stack type templates for https://github.com/sematext/sematext-agent-docker
=> Add Sematext Docker Agent

templates-2.0.json
=> feat(templates): introduce templates version 2

templates-2.0.json
=> fix(edge): remove trailing commas

stacks/cockroachdb/edge/docker-stack.yml, stacks/wordpress/edge/docker-stack.yml, templates-1.20.0.json, templates-2.0.json
Related to https://github.com/portainer/portainer/pull/3812
=> feat(templates): Introduce Edge stack templates

stacks/fdo/docker-stack.yml, templates-2.0.json
=> feat(templates): add FDO app template

stacks/fdo/docker-stack.yml
=> feat(templates): add the manufacturer to the FDO app template

stacks/openamt/docker-compose.yml
Closes [EE-2165](https://portainer.atlassian.net/browse/EE-2165)
=> feat(template) use Portainer postgress image for OpenAMT template [EE-2165]

stacks/openamt/docker-compose.yml
Pins version for the OpenAMT toolkit instead of using latest tag.
=> pin versions for openAMT

stacks/dokku/docker-compose.yml, templates-2.0.json
Close [EE-2700](https://portainer.atlassian.net/browse/EE-2700)
Based on https://dokku.com/docs/getting-started/install/docker/
=> feat(dokku): add dokku templates support

stacks/tosibox/docker-compose.yml, templates-2.0.json
Adds the Tosibox Lock for Container (https://www.tosibox.com/for-sites-tosibox-lock-for-container) as a standalone stack template.
=> add tosibox standalone stack template

templates-2.0.json
=> add opc-router template

edge/softing-edgeconnector-aggregator/docker-compose.yml, edge/softing-edgeconnector-fanuc-cnc/docker-compose.yml, templates-2.0.json
This PR adds two new Edge templates:
* EdgeConnector Aggregator
* EdgeConnector FANUC CNC
These are added as regular container templates and Edge stack templates.
=> feat: add edgeconnector fanuc and aggregator templates

README.md, edge/softing-edgeconnector-aggregator/docker-compose.yml, edge/softing-edgeconnector-fanuc-cnc/docker-compose.yml, templates.json
[EE-6329]
[EE-6329]: https://portainer.atlassian.net/browse/EE-6329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add edgeconnector fanuc and aggregator templates [EE-6329]

.github/workflows/validate.yaml, README.md, schema.json, templates.json
fixes [EE-6391]
[EE-6391]: https://portainer.atlassian.net/browse/EE-6391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ci): validate json [EE-6391]

templates.json
[EE-6458]
[EE-6458]: https://portainer.atlassian.net/browse/EE-6458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(templates): gitlab links and title [EE-6458]

edge/node-red/docker-compose.yml
Adding the Node-Red Compose files
=> Add Node-Red to Edge Templates

edge/emqx/docker-compose.yml, edge/grafana/docker-compose.yml, edge/influxdb/docker-compose.yml, edge/opc-router/docker-compose.yml
=> Add InfluxDB and EMQX

edge/inray-manubes-edge-node/docker-compose.yml, templates-2.0.json
Introduce Inray manubes Edge node template.
=> feat(edge): introduce inray manubes edge node template
